Iteration 6-9
tab/shortly pull request #18
Opened 2024-10-22 18:55 UTC by tab

<details>
  <summary>Инкремент 6: логирование в приложении</summary>

Реализуйте логирование сведений о запросах и ответах на сервере для всех эндпоинтов, которые у вас уже есть. 

- Сведения о запросах должны содержать URI, метод запроса и время, затраченное на его выполнение.
- Сведения об ответах должны содержать код статуса и размер содержимого ответа.

Эту функциональность нужно реализовать через `middleware`. Используйте один из сторонних пакетов для логирования:

- github.com/rs/zerolog,
- go.uber.org/zap,
- github.com/sirupsen/logrus.

Все сообщения логера должны быть на уровне `Info`.
</details>

<details>
  <summary>Инкремент 7: сериализация и десериализация данных</summary>

Добавьте в код сервера новый эндпоинт `POST /api/shorten`, который будет принимать в теле запроса JSON-объект `{"url":"<some_url>"}` и возвращать в ответ объект `{"result":"<short_url>"}`.

Запрос может иметь такой вид:
```
POST http://localhost:8080/api/shorten HTTP/1.1
Host: localhost:8080
Content-Type: application/json
{
  "url": "https://practicum.yandex.ru"
}
```

Ответ может быть таким:
```
HTTP/1.1 201 OK
Content-Type: application/json
Content-Length: 30
{
 "result": "http://localhost:8080/EwHXdJfB"
}
```
</details>

<details>
  <summary>Инкремент 8: сериализация и десериализация данных</summary>

Добавьте поддержку gzip в ваш сервис. Научите его:
- Принимать запросы в сжатом формате (с HTTP-заголовком `Content-Encoding`).
- Отдавать сжатый ответ клиенту, который поддерживает обработку сжатых ответов (с HTTP-заголовком `Accept-Encoding`).

Функция сжатия должна работать для контента с типами `application/json` и `text/html`.
</details>

<details>
  <summary>Инкремент 9: запись и чтение из файла</summary>

Сохраните все сокращённые URL на диск в виде файла. При перезапуске сервера все URL должны быть восстановлены.

Сервер должен принимать соответствующие параметры конфигурации через флаги и переменные окружения:
- Флаг `-f`, переменная окружения `FILE_STORAGE_PATH` — путь до файла, куда сохраняются данные в формате JSON. Имя файла для значения по умолчанию придумайте сами.

```
{"uuid":"1","short_url":"4rSPg8ap","original_url":"http://yandex.ru"}
{"uuid":"2","short_url":"edVPg3ks","original_url":"http://ya.ru"}
{"uuid":"3","short_url":"dG56Hqxm","original_url":"http://practicum.yandex.ru"}
```
</details>

2024-10-25 13:40 UTC, arttet requested changes

2024-10-25 13:40 UTC, arttet commented on internal/app/api/handler.go
> +type ErrorResponse struct {
[CHANGE REQUEST] You need to use it from the `std` library.

2024-10-25 13:40 UTC, arttet commented on internal/app/api/handler.go
> +type Request struct {
[CHANGE REQUEST] Please rename it

2024-10-25 13:40 UTC, arttet commented on internal/app/api/handler.go
> +type Request struct {
[CHANGE REQUEST] It should be in the `dto` package.

2024-10-25 13:40 UTC, arttet commented on internal/app/api/handler.go
> +// NOTE: text/plain request is deprecated
[CLARIFICATION] Why?

2024-10-25 13:40 UTC, arttet commented on internal/app/repository/fs.go
> +	file, err := os.OpenFile(store.FilePath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
[CHANGE REQUEST] We should not use a storage as a file.

2024-10-25 13:40 UTC, arttet commented on internal/logger/logger.go
> +	log  zerolog.Logger
[CHANGE REQUEST] Please don't use global variables.

2024-10-25 14:31 UTC, tab commented on internal/app/api/handler.go
> +// NOTE: text/plain request is deprecated
I'm going to remove the plain/text endpoints at the end of the course and all deprecated code will be removed.
This is a note to make it easier to find this code in the future.

2024-10-28 10:39 UTC, arttet requested changes

2024-10-28 10:39 UTC, arttet commented on cmd/shortener/main.go
> +	errCh := make(chan error, 1)
[CHANGE REQUEST] Please simplify the `main` package

2024-10-28 10:39 UTC, arttet commented on codecov.yaml
> +  - ignore_warnings: true
[CHANGE REQUEST] Please remove it.

2024-10-28 10:39 UTC, arttet commented on docs/swagger.yaml
> +      description: Accepts a JSON object with a URL and returns a shortened URL
[SUGGESTION] Please look at [it](https://github.com/golang-standards/project-layout/tree/master/api)

2024-10-28 10:39 UTC, arttet commented on internal/app/api/handler.go
> +	if err := json.NewDecoder(r.Body).Decode(&params); err != nil {
[SUGGESTION] It can be a part of `validate`.

2024-10-28 10:39 UTC, arttet commented on internal/app/api/handler.go
> +// NOTE: text/plain request is deprecated
Ok, but I am unsure that this API is deprecated.

2024-10-28 10:39 UTC, arttet commented on internal/app/repository/fs.go
> +	return store.loadFromFile()
[CHANGE REQUEST] We should not use `FileRepository`. This is not efficient. Moreover, we should follow the SOLID principals.

2024-10-28 10:39 UTC, arttet commented on internal/app/repository/fs.go
> +	return store.loadFromFile()
https://refactoring.guru/design-patterns/memento

2024-10-28 10:39 UTC, arttet commented on internal/app/repository/memory.go
> +	mu   sync.RWMutex
[SUGGESTION] https://pkg.go.dev/sync#Map

2024-10-31 12:52 UTC, arttet approved these changes

2024-10-31 13:51 UTC, merged